"""Sync schema with models: note_word m2m, note is_pinned/created_at

Revision ID: 0442f6ed1d44
Revises: 58f2e9582a60
Create Date: 2026-07-25 21:31:01.735750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0442f6ed1d44'
down_revision: Union[str, Sequence[str], None] = '58f2e9582a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_word',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word_definitions.id'], ),
    sa.PrimaryKeyConstraint('note_id', 'word_id')
    )
    op.add_column('notes', sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('notes', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('word_definitions_user_id_fkey'), 'word_definitions', type_='foreignkey')
    op.drop_constraint(op.f('word_definitions_note_id_fkey'), 'word_definitions', type_='foreignkey')
    op.drop_column('word_definitions', 'note_id')
    op.drop_column('word_definitions', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Only works against an empty word_definitions table: user_id comes back as
    NOT NULL with no default, and there is no way to recover which user each
    row belonged to once the column has been dropped.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word_definitions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('word_definitions', sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('word_definitions_note_id_fkey'), 'word_definitions', 'notes', ['note_id'], ['id'])
    op.create_foreign_key(op.f('word_definitions_user_id_fkey'), 'word_definitions', 'users', ['user_id'], ['id'])
    op.drop_column('notes', 'created_at')
    op.drop_column('notes', 'is_pinned')
    op.drop_table('note_word')
    # ### end Alembic commands ###
