"""Check declarative mapping

Revision ID: 58f2e9582a60
Revises: c74ae4ac3d9f
Create Date: 2026-06-20 22:09:50.474327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f2e9582a60'
down_revision: Union[str, Sequence[str], None] = 'c74ae4ac3d9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('word_definitions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('word_definitions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('notes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
